config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "home#index"

  resources :users, only: [:show, :edit, :update, :index,:destroy] do
  end

  resources :categories
  # resources :items
  resources :items  do
     resources :bids

   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :item

 after_create :send_email

  def send_email
    UserMailer.with(user: self.item.user).bidding_email.deliver_now 
    UserMailer.with(user: self.user).bidder_email.deliver_now 
  end

  before_create :bid_price
  
  def bid_price
    if self.price < item.price 
      self.errors.add(:base, 'bid price should be greater than item price.')  
      throw :abort  
    end
  end

   before_create :all_bid

  def all_bid
    item.bids.each do |bid|
      if bid.price > self.price
        self.errors.add(:base, 'bid price should be greater than all previous bids.')
        throw :abort
      end
    end
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

    def new
        @bid = Bid.new
    end

    # def new
    #     @item = Item.find(params[:item_id])
    #     @bid = @item.bids
    # end
    
    def create
      @item = Item.find(params[:item_id])
      @bid = Bid.new(bid_params)

      @bid.item_id = @item.id
      @bid.user_id = current_user.id
        @bid.save
        respond_to do |format|
            format.js
            end
    end
         
    def destroy
    
        # @item = Item.find(params[:item_id])
         @bid= Bid.find(params[:id])
        @bid.destroy
        flash[:notice] = 'bid successfully deleted'
        redirect_to item_path(@item)
    end






    def bid_params
        params.require(:bid).permit(:user_id, :item_id, :price)
    end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bid.html.erb
<div >
 <strong>by:</strong><%= bid.user.name  %><br>
<%= bid.price %>

 <%# <%= link_to 'Destroy', item_bid_path(bid), method: :delete, data: { confirm: 'Are you sure?' } %> 
 </div>

 

app/views/bids/_form.html.erb
<%= form_for @bid, url: item_bids_path(@item), remote: true do |f| %>

  <strong><%= f.label :Price %></strong>
 <%= f.number_field :price %><br>
<br>
 <%# <button  class='btn btn-primary' value = 'rating' > Submit </button> %>
<div class="actions">
<%= f.submit "submit" %>
</div>
<%end%>

app/views/bids/create.js.erb
<% if @bid.errors.messages.present? %>
 alert(`<%=  @bid.errors.full_messages.first %>`)
<% else %>
$("#bid_pane").append("<%= j render 'bid', bid: @bid %>");
<% end%>