config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "home#index"

  resources :users, only: [:show, :edit, :update, :index,:destroy] do
  end

  resources :categories
  # resources :items
  resources :items  do
     resources :bids

   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
 mount_uploader :image, ImageUploader

belongs_to :user
belongs_to :category

has_many :bids
has_many :users, through: :bids


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def new
        @item = Item.new
    end

    def create
       
        @item = Item.new(item_params)
        if @item.save!

            flash[notice]= 'item successfully added'
            redirect_to root_path(@item)
        else
            render 'new'
        end
    end

    def show
        @item = Item.find(params[:id]) 
        @bid = Bid.new
    end

    def edit
        @item = Item.find(params[:id]) 
       
    end

    def update
    
        @item = Item.find(params[:id])
        if @item.update(item_params)
            flash[:notice] = "item successfully updated"
            redirect_to items_path
        else
            render 'edit'
        end
    end

    def index
        
        @items = Item.all
    end

 def destroy
    
    @item= Item.find(params[:id])
    @item.destroy
    flash[:notice] = 'item successfully deleted'
    redirect_to items_path(@index)
   end


    private

    def item_params
                params.require(:item).permit [:title,:image, :price, :description, :user_id, :category_id]
    end




end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h3>Edit Item</h3>

<%= @item.errors.full_messages.first if @item.errors.any? %>
 

<%= form_for @item do |f| %> 

      <div class= "mb-3">
      <div class="form-label"><%= f.label :title %></div>
      <%= f.text_field :title, autofocus: true, autocomplete: "Title" %>
      </div>
      
      
      <div class= "mb-3">
      <div class="form-label"><%= f.label :price %></div>
      <%= f.number_field :price, direct_upload: true, autocomplete: "Price" %>
      </div>

      <div class= "mb-3">
      <div class="form-label"><%= f.label :description %></div>
      <%= f.text_field :description, autofocus: true, autocomplete: "Description" %>
      </div>
    
      <div class= "mb-3">
      <div class="form-label"><%= f.label :image %></div>
      <%= f.file_field :image, direct_upload: true, autocomplete: "Image" %>
      </div>

      <%=f.collection_select :category_id, Category.all, :id, :title, promt: true %> 
      <br>
       <br>
      <div class="actions">
      <%= f.submit "submit" %>
      </div>
<% end %>
<br>
<%= link_to 'Back', items_path %> 

app/views/items/index.html.erb
<h1>All Items</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
     <th>Title</th>
     <th>Category</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <%Item.all.each do |item|%>
        <tr>
        <td><%= item.title %></td>
        <td><%= item.category.title %></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <%# <td><%= cl_image_tag(category.image.key, width: 200, height: 100, crop: :scale, effect: "cartoonify") if category.image.attached?%> </td> 
        <td> <%= image_tag (item.image.url),style:"width:50px" if item.image.present?%></td>
        <td><%= link_to 'Show', item_path(item)%> </td>
         <% if item.user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_item_path(item)%></td>
        <td><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
        </tr>
   </tbody>
   </table>
   <%# <br> %>
        <%# <li><a href="/users/sign_out" data-method="delete"> Log Out</a></li> %>
        <%# <%= link_to 'create category', new_category_path %>  <br> 
        <%# <%= link_to 'create item', new_item_path %> 

app/views/items/new.html.erb
<h3> Create New Item</h3>

<%= form_for @item do |f| %> 

      <div class= "mb-3">
      <div class="form-label"><%= f.label :title %></div>
      <%= f.text_field :title, autofocus: true, autocomplete: "Title" %>
      </div>

      <div class= "mb-3">
      <div class="form-label"><%= f.label :price %></div>
      <%= f.number_field :price, direct_upload: true, autocomplete: "Price" %>
      </div>
      
      <div class= "mb-3">
      <div class="form-label"><%= f.label :description %></div>
      <%= f.text_field :description, autofocus: true, autocomplete: "Description" %>
      </div>
      
      <div class= "mb-3">
      <div class="form-label"><%= f.label :image %></div>
      <%= f.file_field :image, direct_upload: true, autocomplete: "Image" %>
      </div>
      
      <%=f.collection_select :category_id, Category.all, :id, :title, promt: true %>
      <br>
      <%= f.text_field :user_id ,class: 'col-lg-4 form-control',
      value: current_user.id, type: :hidden%><br>
      
      <div class="actions">
      <%= f.submit "submit" %>
      </div>
      <% end %>

app/views/items/show.html.erb
<h3 class="text-center">Item Details</h3>
<div class= "container square-box d-flex justify-content-center">
<li>
<p> Title: <%= @item.title %> </p>
<p> Price: <%= @item.price%> </p>
<p> Category: <%= @item.category.title%> </p>
<p> Description: <%= @item.description %> </p>
<%# <p>image:<%= cl_image_tag(@category.image.key,width: 200, height: 100, crop: :scale, effect: "cartoonify") if @category.image.attached? %></p>
<%= image_tag (@item.image.url),style:"width:200px" if @item.image.present? %>

 <%# <div display: flex justify-content> %>

<% if user_signed_in? %>
<h4> Bidding price</h4>

<div id= "bid_pane">
<% @item.bids.each do |bid|%>
<%= render 'bids/bid', bid: bid%>
<br>

<%end%>
</div>

<div>
<h3> Add bidding</h3>
<%= render 'bids/form' %>
</div>

<%end%>


<% if user_signed_in?%>
<%= link_to 'Back', items_path %> 
<% else %>
<%= link_to 'Back', root_path %> 
<%end%>
</li>
</div>